services:
  postgres-db:
    image: postgres
    ports:
      - 5445:5432
    environment:
      POSTGRES_USER: ${DB_USRNM}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NM}
  crm-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
    depends_on:
      - postgres-db
    ports:
      - 8000:8000
    environment:
      POSTGRES_USER: ${DB_USRNM}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NM}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
