from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.utils import generate_unique_id

from ..routes.v1.account_addresses import router as account_addresses_router
from ..routes.v1.account_contracts import router as account_contracts_router
from ..routes.v1.account_entities import router as account_entities_router
from ..routes.v1.account_lists import router as account_lists_router
from ..routes.v1.account_products import router as account_products_router
from ..routes.v1.accounts import router as accounts_router
from ..routes.v1.api_documentation import router as api_doc_router
from ..routes.v1.emails import router as emails_router
from ..routes.v1.entities import router as entities_router
from ..routes.v1.entity_accounts import router as entity_accounts_router
from ..routes.v1.entity_addresses import router as entity_addresses_router
from ..routes.v1.individuals import router as individuals_router
from ..routes.v1.invoice_items import router as invoice_items_router
from ..routes.v1.invoices import router as invoices_router
from ..routes.v1.login import router as login_router
from ..routes.v1.non_individuals import router as non_individuals_router
from ..routes.v1.numbers import router as numbers_router
from ..routes.v1.order_items import router as order_items_router
from ..routes.v1.orders import router as orders_router
from ..routes.v1.product_list_items import router as product_list_items_router
from ..routes.v1.product_lists import router as product_lists_router
from ..routes.v1.products import router as products_router
from ..routes.v1.signup import router as signup_router
from ..routes.v1.sys_users import router as sys_users_router
from ..routes.v1.websites import router as websites_router
from . import constants as cnst

routers = {
    "routers": [
        {
            "name": "api_doc_router",
            "router": api_doc_router,
            "prefix": "",
            "tags": [cnst.TAG_SIGN_UP],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": HTMLResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": False,
        },
        {
            "name": "signup_router",
            "router": signup_router,
            "prefix": "/v1/system-management/sign-up",
            "tags": [cnst.TAG_SIGN_UP],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "login_router",
            "router": login_router,
            "prefix": "/v1/system-management/login",
            "tags": [cnst.TAG_LOGIN],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "sys_users_router",
            "router": sys_users_router,
            "prefix": "/v1/system-management/users",
            "tags": [cnst.TAG_SYS_USER],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "entities_router",
            "router": entities_router,
            "prefix": "/v1/entity-management/entities",
            "tags": [cnst.TAG_ENTITIES],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "individuals_router",
            "router": individuals_router,
            "prefix": "/v1/entity-management/entities",
            "tags": [cnst.TAG_INDIVIDUAL],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": False,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "non_individuals_router",
            "router": non_individuals_router,
            "prefix": "/v1/entity-management/entities",
            "tags": [cnst.TAG_NON_INDIVIDUAL],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": False,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "entity_addresses_router",
            "router": entity_addresses_router,
            "prefix": "/v1/entity-management/entities",
            "tags": [cnst.TAG_ENTITY_ADDRESSES],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "emails_router",
            "router": emails_router,
            "prefix": "/v1/entity-management/entities",
            "tags": [cnst.TAG_ENTITY_EMAILS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "numbers_router",
            "router": numbers_router,
            "prefix": "/v1/entity-management/entities",
            "tags": [cnst.TAG_ENTITY_NUMBERS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "websites_router",
            "router": websites_router,
            "prefix": "",
            "tags": [cnst.TAG_ENTITY_WEBSITES],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "entity_accounts_router",
            "router": entity_accounts_router,
            "prefix": "/v1/entity-management/entities",
            "tags": [cnst.TAG_ENTITY_ACCOUNTS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "accounts_router",
            "router": accounts_router,
            "prefix": "/v1/account-management/accounts",
            "tags": [cnst.TAG_ACCOUNTS],
            "dependencies": "",
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "account_entities_router",
            "router": account_entities_router,
            "prefix": "/v1/account-management/accounts",
            "tags": [cnst.TAG_ACCOUNT_ENTITIES],
            "dependencies": "",
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "account_addresses_router",
            "router": account_addresses_router,
            "prefix": "/v1/account-management/accounts",
            "tags": [cnst.TAG_ACCOUNT_ADDRESSES],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "account_contracts_router",
            "router": account_contracts_router,
            "prefix": "/v1/account-management/accounts",
            "tags": [cnst.TAG_ACCOUNT_CONTRACTS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "account_lists_router",
            "router": account_lists_router,
            "prefix": "/v1/account-management/accounts",
            "tags": [cnst.TAG_ACCOUNT_LISTS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "account_products_router",
            "router": account_products_router,
            "prefix": "/v1/account-management/accounts",
            "tags": [cnst.TAG_ACCOUNT_PRODUCTS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "products_router",
            "router": products_router,
            "prefix": "/v1/product-management/products",
            "tags": [cnst.TAG_PRODUCTS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "products_lists_router",
            "router": product_lists_router,
            "prefix": "/v1/product-management/product-lists",
            "tags": [cnst.TAG_PRODUCT_LISTS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "products_list_items_router",
            "router": product_list_items_router,
            "prefix": "/v1/product-management/product-lists",
            "tags": [cnst.TAG_PRODUCT_LIST_ITEMS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "orders_router",
            "router": orders_router,
            "prefix": "/v1/order-management/orders",
            "tags": [cnst.TAG_ORDERS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "order_items_router",
            "router": order_items_router,
            "prefix": "/v1/order-management/orders",
            "tags": [cnst.TAG_ORDERS_ITEMS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "invoices_router",
            "router": invoices_router,
            "prefix": "/v1/order-management/invoices",
            "tags": [cnst.TAG_INVOICES],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
        {
            "name": "invoice_items_router",
            "router": invoice_items_router,
            "prefix": "/v1/order-management/invoices",
            "tags": [cnst.TAG_INVOICE_ITEMS],
            "dependencies": None,
            "responses": None,
            "deprecated": False,
            "include_in_schema": True,
            "default_response_class": JSONResponse,
            "callbacks": None,
            "generate_unique_id": generate_unique_id,
            "allow_registration": True,
        },
    ]
}
