from uuid import UUID

from sqlalchemy import UUID, Integer, String, text, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .sys_base import SysBase


class NonIndividuals(SysBase):
    """
    This SQLAlchemy model represents a non-individual entity associated with an entity,
    such as a company or organization, and stores information like its name and legal name.

    ivars:
        id: The primary key of the non-individual entity.
        :vartype id: int
        uuid: Unique identifier for the non-individual entity, generated by the database.
        :vartype uuid: UUID
        entity_uuid: Foreign key referencing the associated entity.
        :vartype entity_uuid: UUID
        name: The name of the non-individual entity.
        :vartype name: str
        legal_name: The legal name of the non-individual entity, if applicable.
        :vartype legal_name: str, optional
        entity: Relationship to the `Entities` model.
        :vartype entity: Entities
    """

    __tablename__ = "em_non_individuals"
    __table_args__ = {"schema": "sales"}

    id: Mapped[int] = mapped_column(
        Integer, primary_key=True, nullable=False, autoincrement=True
    )
    uuid: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        unique=True,
        server_default=text("gen_random_uuid()"),
    )

    entity_uuid: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey(column="sales.em_entities.uuid"), nullable=False
    )

    name: Mapped[str] = mapped_column(String(100), nullable=False)
    legal_name: Mapped[str] = mapped_column(String(100), nullable=True)

    # Parent relationship
    entity = relationship("Entities", back_populates="non_individual")
