from uuid import UUID

from sqlalchemy import UUID, Integer, String, text, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .sys_base import SysBase


class Numbers(SysBase):
    """
    This SQLAlchemy model represents a phone number associated with an entity,
    containing details like country code, area code, line number, and extension.

    ivars:
        id: The primary key of the phone number record.
        :vartype id: int
        uuid: Unique identifier for the phone number, generated by the database.
        :vartype uuid: UUID
        entity_uuid: Foreign key referencing the associated entity.
        :vartype entity_uuid: UUID
        sys_value_type_uuid: An optional identifier for the system value type.
        :vartype sys_value_type_uuid: UUID, optional
        country_code: The country code part of the phone number (e.g., "+1" for US).
        :vartype country_code: str, optional
        area_code: The area code part of the phone number.
        :vartype area_code: str, optional
        line_number: The line number part of the phone number.
        :vartype line_number: str, optional
        extension: The extension part of the phone number, if available.
        :vartype extension: str, optional
        entity: Relationship to the `Entities` model.
        :vartype entity: Entities
    """

    __tablename__ = "em_numbers"
    __table_args__ = {"schema": "sales"}

    id: Mapped[int] = mapped_column(
        Integer, primary_key=True, nullable=False, autoincrement=True
    )
    uuid: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, server_default=text("gen_random_uuid()")
    )

    entity_uuid: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey(column="sales.em_entities.uuid"), nullable=False
    )
    sys_value_type_uuid: Mapped[UUID] = mapped_column(UUID(as_uuid=True), nullable=True)
    country_code: Mapped[str] = mapped_column(String(1), nullable=True)
    area_code: Mapped[str] = mapped_column(String(3), nullable=True)
    line_number: Mapped[str] = mapped_column(String(4), nullable=True)
    extension: Mapped[str] = mapped_column(String(10), nullable=True)

    # Parent relationship
    entity = relationship("Entities", back_populates="numbers")
