from datetime import datetime
from uuid import uuid4

from sqlalchemy import TIMESTAMP, UUID, Integer, String, text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.sys_base import SysBase


class SysUsers(SysBase):
    """
    Represents a system user in the sales system.

    This SQLAlchemy model stores user information, including their personal details, authentication fields, and account status.

    ivars:
        id: The primary key of the system user.
        :vartype id: int
        uuid: Unique identifier for the user, generated by the database.
        :vartype uuid: UUID
        first_name: The first name of the user.
        :vartype first_name: str
        last_name: The last name of the user.
        :vartype last_name: str
        email: The email address of the user, which must be unique.
        :vartype email: str
        username: The username of the user, used for authentication.
        :vartype username: str
        password: The password of the user for authentication, stored securely.
        :vartype password: str
        disabled_at: Timestamp indicating when the user's account was disabled, if applicable.
        :vartype disabled_at: datetime, optional
    """

    __tablename__ = "sys_users"
    __table_args__ = {"schema": "sales"}

    id: Mapped[int] = mapped_column(
        Integer, primary_key=True, nullable=False, autoincrement=True
    )
    uuid: Mapped[uuid4] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        server_default=text("gen_random_uuid()"),
        unique=True,
    )

    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    email: Mapped[str] = mapped_column(String(325), nullable=False, unique=True)
    username: Mapped[str] = mapped_column(String(325), nullable=False)
    password: Mapped[str] = mapped_column(String(325), nullable=False)
    disabled_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )
